[project]
name = "postgresql-practice"
version = "0.1.0"
description = "Basic Python Script For Load Data From Excel To PostgreSQL Database"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pandas>=2.3.0",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.1.0",
]
